### ISSUE TITLE
busfactor

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/governance-and-guidance#10]
We need to figure out how to share secrets. Since we are starting to deploy things, this is important.

**Comment by khionu** [comment]
A default for now could be Keybase.io.

**Comment by rajivshah3** [comment]
[Hashicorp Vault](https://www.hashicorp.com/products/vault/)  might be a good option, but requires you to set up your own server for it. It’s also open source. 

1Password might be an easier option if you’re ok with a closed source, hosted option.

**Comment by nklayman** [comment]
Bitwarden is an open source alternative to 1password that offers free hosting options.

**Comment by khionu** [comment]
Vault is excessive and high maintenance. It was considered for Amethyst, but deemed too much of a risk because of the requirements to not get locked out of your own instance/data. Otherwise, yes, it would be a decent option.

Bitwarden would not be free for us, as our needs go above what they offer for free. Last I knew self-hosting did not remove those costs, though I just asked in their Gitter to double check.

**Comment by Beanow** [comment]
Currently I'm trying out a self-hosted [passbolt](https://passbolt.com/) under the https://teamopen.org/ name. So far it does the job and has comprehensive access control for groups and individuals :+1:

I've also tried bitwarden and think passbolt is easier to host. Also worried bitwarden itself may suffer from bus-factor risks. (compare [this](https://github.com/bitwarden/server/graphs/contributors) with [this](https://github.com/passbolt/passbolt_api/graphs/contributors))

> Hashicorp Vault might be a good option, but requires you to set up your own server for it. It’s also open source.

On the server point, I have the idea to use https://teamopen.org/ for shared infrastructure you commonly need in OSS development. Such as sharing secrets. So perhaps this is something we can collaborate on.

That said, Vault looks like a really cool system. But isn't something designed for shared infrastructure, because it uses an in-memory master key and is expected to be serviced by high-trust internal security experts (see [architecture doc](https://www.vaultproject.io/docs/internals/architecture.html)). Where passbolt uses GPG for E2E encryption. So I wouldn't feel comfortable running anything more than an (encrypted) storage replica :sweat_smile:

**Comment by mralve** [comment]
1+ for Keybase.io.

**Comment by khionu** [comment]
I've gotten confirmation, Bitwarden still requires a license to use, unless we rip the license-checking code out, which the license on the codebase does let us do... but it's a rather immoral thing, as an OSS project ourselves.

**Comment by khionu** [comment]
So, Keybase.io or Passbolt, I guess are our two current options? The former is 100% free and hosted for us, with true E2E encryption.

**Comment by nklayman** [comment]
Hosting does cost money though, so the only completely free option is a non-self hosted solution. In addition, bitwarden premium costs like $10 a year versus $5 a month for a digitalocean droplet.

**Comment by tensor-programming** [comment]
We've already got a digital ocean droplet; we could potentially piggyback on top of that.

**Comment by khionu** [comment]
Then we have to maintain Passbolt, while we wouldn't need to maintain Keybase.io

**Comment by nothingismagick** [comment]
I definitely don't think it's a good idea to mix production services with org infrastructure on the same underpowered VM. Would rather spin up a new droplet. But we also need a mail service. I think those two together would be OK.

**Comment by nothingismagick** [comment]
But in the sense of opsec, we shouldn't discuss the details here in this public issue I suppose.

**Comment by tensor-programming** [comment]
Mail and Front facing apps shouldn't be an issue on the same VM.  Tons of apps and organizations work that way.  Even something like keybase wouldn't be a problem, its not very heavy and its not something that could be located with a proper DNS setup.
