### ISSUE TITLE
"Sponsored" Plugin PRs

### ISSUE THREAD

**Issue by lorenzolewis** [tauri-apps/governance-and-guidance#42]
We currently have two pending plugin PRs that are done in collaboration with [CrabNebula](https://crabnebula.dev/) and [Impierce Technologies](https://www.impierce.com/):

- https://github.com/tauri-apps/plugins-workspace/pull/504
- https://github.com/tauri-apps/plugins-workspace/pull/536

The particular parts to bring attention to are here:

- https://github.com/tauri-apps/plugins-workspace/blob/4f8c795a85c400adf96659d2d735a22dff8b9be5/plugins/deep-link/README.md?plain=1#L139
- https://github.com/tauri-apps/plugins-workspace/blob/c684a318c9b3e0a0b0fea06ce23af1510a248a45/plugins/barcode-scanner/README.md?plain=1#L75

These areas render out into the respective READMEs like so:
<img width="659" alt="Screenshot 2023-09-08 at 11 09 05" src="https://github.com/tauri-apps/governance-and-guidance/assets/15347255/238cc01c-b4d7-4445-940d-3c5bab3bf89c">

While we have approved CrabNebula as a sponsor inline with our current precedent (pending CrabNebula's thumbs-up for release), we have not had similar conversations for Impierce Technologies (although this is not to say we aren't open to those conversations). 

To the point on current precedent, we have currently only highlighted "Sponsors" via our [website](https://tauri.app/): 

<img width="1125" alt="Screenshot 2023-09-08 at 11 11 07" src="https://github.com/tauri-apps/governance-and-guidance/assets/15347255/12556aaa-27e0-4316-b22a-91546522bc9f">

@Beanow outlined a few open questions in [his comment](https://github.com/tauri-apps/plugins-workspace/pull/536#discussion_r1319647547) on the barcode scanner PR that I'll attempt to summarize here:

- To @lucasfernog: Have both CrabNebula and Impierce Technologies given the thumbs-up on this?
- Was there a discussion in Tauri around how the logos would be placed and formatted?
- What would a different company have to do to get the same treatment of getting their plugin adopted by @tauri-apps as an "official" plugin with sponsor callouts and everything?
- Who is responsible for future maintenance, etc. of the plugin?

To echo what I believe is @Beanow 's sentiment, I don't personally want to hold these PRs up with this conversation. However I would recommend getting a gut-check from a non-CrabNebula board member on this as it's our first time in this area. 

I would also like to have a larger discussion as mentioned before about how we define a Sponsor and opening up opportunities for a "Partner"-type relationship between Tauri and other entities. With that in mind I would like to reserve the right to modify the README in those respective PRs pending that conversation and any impacts that may have.

Lastly, while this is a fantastic opportunity to grow Tauri's functionality and I would love to see more collaborations like this in the future, I would like to be VERY mindful of development capacity to maintain not only these two plugins, but also any further plugins that could come up in the future. One potential option (that these two plugins may or may not fall into) would be to highlight any "community" plugins on a page such as https://beta.tauri.app/2/guide/list/#community-resources. This ensures we give visibility to the plugins but also allows Tauri to not necessarily take on maintenance of them if the organization as a whole deems that we don't have the capacity or interest to do so. 

---

The current ask is:

1. Could a non-CrabNebula board member please weight in on if the current state of the PRs linked above would be appropriate to merge into the Tauri codebase
2. What future conversations (if any) do we need to discuss in order to more properly define this type of arrangement in hopes of similar opportunities coming up in the future?

**Comment by lucasfernog** [comment]
The plugins were developed under a sponsorship collaboration between CN and Impierce Technologies. Basically we made a deal that made it possible to give back those plugins to the community instead of having them closed source. I should've started this discussion before opening that PR, sorry about that. I feel I should've also used my CN account to push that PR to make it clearer.

I like the idea of moving the scanner plugin to a community maintained workspace repository as it's a more specific use case, though the deep link plugin is definitely vital for Tauri core.

**Comment by lorenzolewis** [comment]
Thanks @lucasfernog 💜 Are there any details on future expectations for maintenance that could be shared to give a bit more context?

**Comment by lucasfernog** [comment]
The deep link plugin is one of the most requested Tauri features, so I feel it should be maintained by Tauri. As far as I know only this first iteration was sponsored.
As the scanner plugin is more specific, either we move it to a community repository or mark it as feature complete, that's the way I see it. Any other insight @nothingismagick ?

**Comment by Beanow** [comment]
Hey @jbolda @wravery @zackarychapple sorry to urge you but there is urgency :laughing:

Repeating from Lorenzo:
1. Could a non-CrabNebula board member please weight in on if the current state of the PRs linked above would be appropriate to merge into the Tauri codebase.
2. What future conversations (if any) do we need to discuss in order to more properly define this type of arrangement in hopes of similar opportunities coming up in the future?

Especially 1. is a **blocker** right now, so I would love to hear from at least one person a clear cut:
Can we proceed? / Do we request changes?

**Comment by wravery** [comment]
I like what they're doing with this contribution, and I think we should figure out how to encourage this without creating a confusing precedent. Plus, the plugins themselves seem very useful and valuable to the community.

Perhaps "sponsored" is the wrong term, since it sounds like we expect to own maintaining them. Sponsorship implies ongoing support to me, this is more like a one time donation. How about acknowledging them as "contributed by," instead?

Maybe instead of or in addition to the note in the README which ends up embedded in the project repo, how about making a blog post highlight the new functionality and thanking the contributors for their generosity? That way they get a PR boost and recognition without the implication of ongoing support, and the organization doesn't establish a tricky sponsorship backdoor.

**Comment by Beanow** [comment]
Thank you @wravery!

@nothingismagick @lucasfernog does that look like a suitable alternative that can be adopted **as-is**?
Emphasis on the latter, because if we're all happy with that, it seems like the quickest path forward.

(Please ping additional decision makers for me if I'm skipping anyone.)

**Comment by lucasfernog** [comment]
I love this idea, I think it's a good compromise for Tauri and "sponsors".

**Comment by lucasfernog** [comment]
https://github.com/tauri-apps/plugins-workspace/blob/deep-link/plugins/deep-link/README.md#contributed-by
https://github.com/lucasfernog/plugins-workspace/blob/feat/scanner/plugins/barcode-scanner/README.md#contributed-by

It even looks better tbh :D

**Comment by Beanow** [comment]
Repeating for extra visibility:
https://github.com/tauri-apps/plugins-workspace/pull/536#discussion_r1325770710
https://github.com/tauri-apps/plugins-workspace/pull/536#issuecomment-1719230116

Replies from https://github.com/JelleMillenaar CEO of Impierce Technologies.

**Comment by Beanow** [comment]
I think we've resolved the questions. To summarize:

Have both CrabNebula and Impierce Technologies given the thumbs-up on this?
  - [x] CrabNebula, since they're PR authors and from multiple chats.
  - [x] Impierce Technologies, in this comment:
  https://github.com/tauri-apps/plugins-workspace/pull/536#discussion_r1325770710

Was there a discussion in Tauri around how the logos would be placed and formatted?
  - [x] Not beforehand, but we have now in this thread.
  - [x] And confirmation [the placement is non-conditional](https://github.com/tauri-apps/plugins-workspace/pull/536#issuecomment-1719230116), so there is room to revisit later.

What would a different company have to do to get the same treatment of getting their plugin adopted by @tauri-apps as an "official" plugin with sponsor callouts and everything?
  - [x] The excellent :rocket: suggestion [to use "contributed by"](https://github.com/tauri-apps/governance-and-guidance/issues/42#issuecomment-1718009509) I think helps to make this more accessible in the future.
  - [ ] Though there is room to think about and clarify contributions and sponsorships generally.
         I think that can be for a later discussion though and I think isn't a blocker here.

Who is responsible for future maintenance, etc. of the plugin?
  - [x] In principle, Tauri maintains the plugins.
  - [x] And explaining [whether we should](https://github.com/tauri-apps/governance-and-guidance/issues/42#issuecomment-1711476057)
  
Could a non-CrabNebula board member please weight in on if the current state of the PRs linked above would be appropriate to merge into the Tauri codebase
  - [x] Done! https://github.com/tauri-apps/governance-and-guidance/issues/42#issuecomment-1718009509
    And with modifications could be merged.

What future conversations (if any) do we need to discuss in order to more properly define this type of arrangement in hopes of similar opportunities coming up in the future?
  - [ ] This remains open. The main topic raised I believe is: "how could another contributor achieve the same"?
  
---

The open points I think fit best in an overall sponsorships / contributions discussion.
So with that I'll close this issue as resolved! :100:
Thanks all for your help.
